export const profile = {
	name: 'Андрей Боженков',
	title: 'Frontend-разработчик (Next.js, React.js)',
	location: 'Санкт-Петербург, Россия',
	email: 'jarefyx@gmail.com',
	phone: '+79086605214',
	telegram: 't.me/drag11',
	whatsapp: '79086605214',
	github: 'github.com/JaredNil',
	website: 'jarefy.ru',
	about: `
    Работаю Web-разработчиком уже 6 лет. Умею работать с тяжелыми задачами, предлагая
	оптимальные пути решения проблем. Коммуникабелен, и при необходимости всегда на
	связи.
	В свободное время увлекаюсь продвинутой кулинарией, философией и велопрогулками.
	До web-разработки позиционировал себя как С++ инженер, что дало мне довольно широкий
	фундамент для проектирования кода.
	В будущем планирую увеличить экспертность в проектировании сложных микросервисных
	систем на JavaScript, Go, а также в управленческих вопросах.
	Pet-project: open-source клиент для потоковой музыки как альтернативу Spotify —
	jarefy.ru (там же полное резюме).
  `,
	experience: [
		{
			company: 'Военный инновационный технополис ЭРА',
			role: 'Frontend-разработчик (React)',
			period: 'Июль 2024 — Июль 2025',
			achievements: [
				'Внедрил конкуррентный рендеринг (React 18) для улучшения отзывчивости интерфейса и снижения времени загрузки',
				'Реализовал на RxJS потоковую обработку видео из WebSocket с автоматическим реконнектом и резервным long-polling при обрыве соединения',
				'Внедрил методологию Feature-Sliced Design в проект, Tanstack Query для управления состоянием и кэшем приложения',
				'Поднял BFF-сервис (Backend for Frontend) на Go для проксирования WebSocket-соединений и потоковой передачи медиаданных между React-клиентом и поставщиком данных',
			],
			stack: [
				'React 18/19',
				'Tanstack Query',
				'Rx.js',
				'React Router',
				'JavaScript (ES6+)',
				'TypeScript 5',
				'SCSS',
				'Vite',
				'ESLint',
				'Tailwind',
				'Docker',
				'Go',
				'Chi',
			],
		},
		{
			company: 'ООО CITYAPP',
			role: 'Frontend-разработчик (React/Next.js) с опытом backend (Nest.js)',
			period: 'Март 2020 — Февраль 2023',
			achievements: [
				'Внедрил в команду шаблоны ISR и SSR на Next.js для разработки интерфейсов и ускорил TTI на 26% (время до интерактивности)',
				'Разработал BFF-прослойки на Nest.js и Next.js API: маршрутизация, логгирование, аутентификация с хранением сессий, сокрытие внутренней архитектуры от фронта',
				'Реализовал state-архитектуру: Redux Toolkit Query для кеширования и синхронизации RESTful-данных; RxJS — для управления реактивными потоками и асинхронными событиями',
				'Согласовал в команде архитектуру Feature Sliced Design и методологии качества Husky, ESLint для поддержания единого стиля кода; оптимизировал сборку Webpack под задачи проектов (снизил размер бандла проекта на 24%)',
				'Настроил CI/CD и пирамиду тестирования: Unit, Integration, Screenshot (Storybook)',
				'Создал шаблон интеграции 3D-моделей (Three.js) и анимации (React-spring, GSAP) для визуально сложных веб-приложений',
			],
			stack: [
				'Next.js',
				'React.js',
				'Redux Toolkit Query',
				'Tanstack Query',
				'JavaScript (ES6+)',
				'TypeScript',
				'CSS3/SCSS/SASS',
				'Tailwind',
				'GSAP',
				'Three.js',
				'React Three Fiber',
				'Git',
				'Jest',
				'React Testing Library',
				'Webpack',
				'Vite',
				'ESLint',
				'Figma',
				'Node.js',
				'Nest.js',
				'SQL',
			],
		},
	],
	skills: [
		'Git',
		'PostgreSQL',
		'React',
		'Next.js',
		'HTML5',
		'RTK Query',
		'Tanstack query',
		'Zustand',
		'storybook',
		'CI/CD',
		'Scrum',
		'SQL',
		'JavaScript',
		'TypeScript',
		'Gitlab',
		'MobX',
		'tailwind',
		'Jest',
		'SSR',
		'Webpack',
		'Vite',
		'Node.js',
		'WebSocket',
		'Docker',
		'SEO-оптимизация',
		'CSS',
		'Angular',
		'REST',
		'Оптимизация кода',
		'Redux',
	],
}
